name: vit_gpt_dart_api
description: Functions to access the Open API endpoints
version: 1.8.1
repository: https://github.com/TimeLord2010/vit_gpt_dart_api

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  vit_dart_extensions: ^2.5.0
  vit_logger: ^2.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
