name: vit_gpt_dart_api
description: Functions to access the Open API endpoints
version: 6.0.4
repository: https://github.com/TimeLord2010/vit_gpt_dart_api

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  vit_dart_extensions: ^4.0.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^6.0.0
  mockito: ^5.4.5
  test: ^1.24.0
